//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "Areaprovince.h"
#import "AreaHelper.h"
#import "AreagetProvinceByIdResponse.h"


@implementation AreagetProvinceByIdResponse
    @synthesize _return;

+ (AreagetProvinceByIdResponse *)createWithXml:(DDXMLElement *)__node __request:(AreaRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(AreaRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([AreaHelper hasValue:__node name:@"return"])
        {
            self._return = (Areaprovince*)[__request createObject:[AreaHelper getNode:__node name:@"return"] type:[Areaprovince class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(AreaRequestResultHandler*) __request
{

             
        DDXMLElement* ___returnItemElement=[__request writeElement:_return type:[Areaprovince class] name:@"return" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___returnItemElement!=nil)
        {
            [self._return serialize:___returnItemElement __request: __request];
        }


}
@end
