//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "AreafindProvinceResponse.h"
#import "AreagetAllProvinceResponse.h"
#import "Areacity.h"
#import "AreafindCityResponse.h"
#import "Areaprovince.h"
#import "DDXML.h"

@class AreaRequestResultHandler;

@protocol AreaSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface AreaAreaServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createfindProvinceRequest:(NSString*) arg0 arg1:(NSString*) arg1 __request:(AreaRequestResultHandler*) __request;
-(AreafindProvinceResponse*) findProvince:(NSString*) arg0 arg1:(NSString*) arg1 __error:(NSError**) __error;
-(AreaRequestResultHandler*) findProvinceAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id) __target __handler:(SEL) __handler;
-(AreaRequestResultHandler*) findProvinceAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id<AreaSoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetAllProvinceRequest:(AreaRequestResultHandler*) __request;
-(AreagetAllProvinceResponse*) getAllProvince:(NSError**) __error;
-(AreaRequestResultHandler*) getAllProvinceAsync:(id) __target __handler:(SEL) __handler;
-(AreaRequestResultHandler*) getAllProvinceAsync:(id<AreaSoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetCityByIdRequest:(NSString*) arg0 __request:(AreaRequestResultHandler*) __request;
-(Areacity*) getCityById:(NSString*) arg0 __error:(NSError**) __error;
-(AreaRequestResultHandler*) getCityByIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(AreaRequestResultHandler*) getCityByIdAsync:(NSString*) arg0 __target:(id<AreaSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfindCityRequest:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __request:(AreaRequestResultHandler*) __request;
-(AreafindCityResponse*) findCity:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __error:(NSError**) __error;
-(AreaRequestResultHandler*) findCityAsync:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __target:(id) __target __handler:(SEL) __handler;
-(AreaRequestResultHandler*) findCityAsync:(NSString*) arg0 arg1:(NSString*) arg1 arg2:(NSString*) arg2 __target:(id<AreaSoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetProvinceByIdRequest:(NSString*) arg0 __request:(AreaRequestResultHandler*) __request;
-(Areaprovince*) getProvinceById:(NSString*) arg0 __error:(NSError**) __error;
-(AreaRequestResultHandler*) getProvinceByIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(AreaRequestResultHandler*) getProvinceByIdAsync:(NSString*) arg0 __target:(id<AreaSoapServiceResponse>) __target;
-(AreaRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(AreaRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(AreaRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(AreaRequestResultHandler*) requestMgr callback:(void (^)(AreaRequestResultHandler *)) callback;

@end
