//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class Areaprovince;
#import "AreaRequestResultHandler.h"
#import "DDXML.h"



@interface AreagetProvinceByIdResponse : NSObject 


@property (retain,nonatomic,getter=get_return) Areaprovince* _return;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(AreaRequestResultHandler*) __request;
+(AreagetProvinceByIdResponse*) createWithXml:(DDXMLElement*)__node __request:(AreaRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(AreaRequestResultHandler*) __request;
@end