//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "AreaRequestResultHandler.h"
#import "DDXML.h"



@interface Areacity : NSObject 


@property (retain,nonatomic,getter=get_id) NSString* _id;

@property (retain,nonatomic,getter=getJianpin) NSString* jianpin;

@property (retain,nonatomic,getter=getName) NSString* name;

@property (retain,nonatomic,getter=getProvinceId) NSString* provinceId;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(AreaRequestResultHandler*) __request;
+(Areacity*) createWithXml:(DDXMLElement*)__node __request:(AreaRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(AreaRequestResultHandler*) __request;
@end