//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "BaseFoodRequestResultHandler.h"
#import "DDXML.h"



@interface BaseFoodbaseFood : NSObject 


@property (retain,nonatomic,getter=getAlias) NSString* alias;

@property (retain,nonatomic,getter=getB1) NSString* b1;

@property (retain,nonatomic,getter=getB2) NSString* b2;

@property (retain,nonatomic,getter=getB6) NSString* b6;

@property (retain,nonatomic,getter=getCalcium) NSString* calcium;

@property (retain,nonatomic,getter=getCarbohydrate) NSString* carbohydrate;

@property (retain,nonatomic,getter=getCholesterol) NSString* cholesterol;

@property (retain,nonatomic,getter=getCreateTime) NSDate* createTime;

@property (retain,nonatomic,getter=getDietaryFiber) NSString* dietaryFiber;

@property (retain,nonatomic,getter=getEnergy) NSString* energy;

@property (retain,nonatomic,getter=getFat) NSString* fat;

@property (retain,nonatomic,getter=getFerri) NSString* ferri;

@property (retain,nonatomic,getter=getFolate) NSString* folate;

@property (retain,nonatomic,getter=getFoodName) NSString* foodName;

@property (retain,nonatomic,getter=getFoodType) NSString* foodType;

@property (retain,nonatomic,getter=getFoodTypeName) NSString* foodTypeName;

@property (retain,nonatomic,getter=getGlycemic) NSString* glycemic;

@property (retain,nonatomic,getter=get_id) NSString* _id;

@property (retain,nonatomic,getter=getIntroduce) NSString* introduce;

@property (retain,nonatomic,getter=getIodine) NSString* iodine;

@property (retain,nonatomic,getter=getNutrition) NSString* nutrition;

@property (retain,nonatomic,getter=getNutritionTrait) NSString* nutritionTrait;

@property (retain,nonatomic,getter=getPicture) NSString* picture;

@property (retain,nonatomic,getter=getProtein) NSString* protein;

@property (retain,nonatomic,getter=getRemark) NSString* remark;

@property (retain,nonatomic,getter=getVitaminA) NSString* vitaminA;

@property (retain,nonatomic,getter=getVitaminC) NSString* vitaminC;

@property (retain,nonatomic,getter=getZinc) NSString* zinc;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(BaseFoodRequestResultHandler*) __request;
+(BaseFoodbaseFood*) createWithXml:(DDXMLElement*)__node __request:(BaseFoodRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(BaseFoodRequestResultHandler*) __request;

-(void)turnOnHighlight;

- (void)shutDownHighlight;

- (BOOL)shouldIHighlight;

@end