//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "BaseFoodbaseFood.h"
#import "BaseFoodjsonData.h"
#import "BaseFoodpageParam.h"
#import "DDXML.h"

@class BaseFoodRequestResultHandler;

@protocol BaseFoodSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface BaseFoodBaseFoodServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetByIdRequest:(NSString*) arg0 __request:(BaseFoodRequestResultHandler*) __request;
-(BaseFoodbaseFood*) getById:(NSString*) arg0 __error:(NSError**) __error;
-(BaseFoodRequestResultHandler*) getByIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(BaseFoodRequestResultHandler*) getByIdAsync:(NSString*) arg0 __target:(id<BaseFoodSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfindBaseFoodRequest:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __request:(BaseFoodRequestResultHandler*) __request;
-(BaseFoodjsonData*) findBaseFood:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __error:(NSError**) __error;
-(BaseFoodRequestResultHandler*) findBaseFoodAsync:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __target:(id) __target __handler:(SEL) __handler;
-(BaseFoodRequestResultHandler*) findBaseFoodAsync:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __target:(id<BaseFoodSoapServiceResponse>) __target;
-(BaseFoodRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(BaseFoodRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(BaseFoodRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(BaseFoodRequestResultHandler*) requestMgr callback:(void (^)(BaseFoodRequestResultHandler *)) callback;

@end
