//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "BaseFoodHelper.h"
#import "BaseFoodjsonData.h"


@implementation BaseFoodjsonData
    @synthesize errorTrace;
    @synthesize extData;
    @synthesize msg;
    @synthesize rows;
    @synthesize success;
    @synthesize total;

+ (BaseFoodjsonData *)createWithXml:(DDXMLElement *)__node __request:(BaseFoodRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.rows =[NSMutableArray array];
        self.total =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(BaseFoodRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([BaseFoodHelper hasValue:__node name:@"errorTrace"])
        {
            self.errorTrace = [[BaseFoodHelper getNode:__node name:@"errorTrace"] stringValue];
        }
        if([BaseFoodHelper hasValue:__node name:@"extData"])
        {
            self.extData = [[BaseFoodHelper getNode:__node name:@"extData"] stringValue];
        }
        if([BaseFoodHelper hasValue:__node name:@"msg"])
        {
            self.msg = [[BaseFoodHelper getNode:__node name:@"msg"] stringValue];
        }
        if([BaseFoodHelper hasValue:__node name:@"rows"])
        {
            NSArray* __items=[__node elementsForName:@"rows"];
            for (DDXMLElement* __item in __items) {
                [self.rows addObject:[__item stringValue]];
            }
        }
        if([BaseFoodHelper hasValue:__node name:@"success"])
        {
            self.success = [[[BaseFoodHelper getNode:__node name:@"success"] stringValue] boolValue];
        }
        if([BaseFoodHelper hasValue:__node name:@"total"])
        {
            self.total = (int)[[[BaseFoodHelper getNode:__node name:@"total"] stringValue] integerValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(BaseFoodRequestResultHandler*) __request
{

             
        DDXMLElement* __errorTraceItemElement=[__request writeElement:errorTrace type:[NSString class] name:@"errorTrace" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__errorTraceItemElement!=nil)
        {
            [__errorTraceItemElement setStringValue:self.errorTrace];
        }
             
        DDXMLElement* __extDataItemElement=[__request writeElement:extData type:[NSString class] name:@"extData" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__extDataItemElement!=nil)
        {
            [__extDataItemElement setStringValue:self.extData];
        }
             
        DDXMLElement* __msgItemElement=[__request writeElement:msg type:[NSString class] name:@"msg" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__msgItemElement!=nil)
        {
            [__msgItemElement setStringValue:self.msg];
        }
             
        if(self.rows!=nil)
        {
            for (NSString* __item in self.rows) {
                DDXMLElement* __rowsItemElement=[__request writeElement:rows type:[NSString class] name:@"rows" URI:@"" parent:__parent skipNullProperty:NO];
                if(__rowsItemElement!=nil)
                {
                    [__rowsItemElement setStringValue:__item];
                }
            }
        }
             
        DDXMLElement* __successItemElement=[__request writeElement:@"success" URI:@"" parent:__parent];
        [__successItemElement setStringValue:[BaseFoodHelper toBoolStringFromBool:self.success]];
             
        DDXMLElement* __totalItemElement=[__request writeElement:@"total" URI:@"" parent:__parent];
        [__totalItemElement setStringValue: [NSString stringWithFormat:@"%i", self.total]];


}
@end
