//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "BaseFoodpageParam.h"
#import "BaseFoodbaseFood.h"
#import "BaseFoodHelper.h"
#import "BaseFoodfindBaseFood.h"


@implementation BaseFoodfindBaseFood
    @synthesize arg0;
    @synthesize arg1;

+ (BaseFoodfindBaseFood *)createWithXml:(DDXMLElement *)__node __request:(BaseFoodRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(BaseFoodRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([BaseFoodHelper hasValue:__node name:@"arg0"])
        {
            self.arg0 = (BaseFoodpageParam*)[__request createObject:[BaseFoodHelper getNode:__node name:@"arg0"] type:[BaseFoodpageParam class]];
        }
        if([BaseFoodHelper hasValue:__node name:@"arg1"])
        {
            self.arg1 = (BaseFoodbaseFood*)[__request createObject:[BaseFoodHelper getNode:__node name:@"arg1"] type:[BaseFoodbaseFood class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(BaseFoodRequestResultHandler*) __request
{

             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[BaseFoodpageParam class] name:@"arg0" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [self.arg0 serialize:__arg0ItemElement __request: __request];
        }
             
        DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[BaseFoodbaseFood class] name:@"arg1" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg1ItemElement!=nil)
        {
            [self.arg1 serialize:__arg1ItemElement __request: __request];
        }


}
@end
