//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "BaseFoodBaseFoodServiceImplServiceSoapBinding.h"
#import "BaseFoodRequestResultHandler.h"
#import "BaseFoodHelper.h"

@implementation BaseFoodBaseFoodServiceImplServiceSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=[NSString stringWithFormat:@"%@%@",WebserviceUrl,@"baseFood"];
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(BaseFoodRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(BaseFoodRequestResultHandler*) CreateRequestResultHandler
{
    return [[BaseFoodRequestResultHandler alloc]init];
}
-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(BaseFoodRequestResultHandler*) __request
{
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(BaseFoodRequestResultHandler*) requestMgr callback:(void (^)(BaseFoodRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) creategetByIdRequest:(NSString*) arg0 __request:(BaseFoodRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getById" URI:@"http://service.food.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [__arg0ItemElement setStringValue:arg0];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(BaseFoodRequestResultHandler*) getByIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    BaseFoodRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetByIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(BaseFoodRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[BaseFoodHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (BaseFoodbaseFood*)[__request createObject:__result type:[BaseFoodbaseFood class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(BaseFoodRequestResultHandler*) getByIdAsync:(NSString*) arg0 __target:(id<BaseFoodSoapServiceResponse>) __target
{
    BaseFoodRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetByIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(BaseFoodRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[BaseFoodHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:(BaseFoodbaseFood*)[__request createObject:__result type:[BaseFoodbaseFood class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(BaseFoodbaseFood*) getById:(NSString*) arg0 __error:(NSError**) __error 
{
    BaseFoodRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetByIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[BaseFoodHelper getResultElement:__request.OutputBody name:@"return"];
    return (BaseFoodbaseFood*)[__request createObject:__result type:[BaseFoodbaseFood class]];
}
-(NSMutableURLRequest*) createfindBaseFoodRequest:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __request:(BaseFoodRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"findBaseFood" URI:@"http://service.food.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[BaseFoodpageParam class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [arg0 serialize:__arg0ItemElement __request: __request];
        }
             
        DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[BaseFoodbaseFood class] name:@"arg1" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg1ItemElement!=nil)
        {
            [arg1 serialize:__arg1ItemElement __request: __request];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(BaseFoodRequestResultHandler*) findBaseFoodAsync:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __target:(id) __target __handler:(SEL) __handler
{
    BaseFoodRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindBaseFoodRequest:arg0 arg1: arg1 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(BaseFoodRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[BaseFoodHelper getResultElement:__request.OutputBody name:@"return"];
        NSArray *rows = [__result elementsForName:@"rows"];
        NSMutableArray *foodArray = [[NSMutableArray alloc] init];
        for (DDXMLElement *row in rows){
            id food = [__request createObject:row type:[BaseFoodbaseFood class]];
            [foodArray addObject:food];
        }
        BaseFoodjsonData *foods = (BaseFoodjsonData*)[__request createObject:__result type:[BaseFoodjsonData class]];
        foods.rows = foodArray;
        __res = foods;
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(BaseFoodRequestResultHandler*) findBaseFoodAsync:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __target:(id<BaseFoodSoapServiceResponse>) __target
{
    BaseFoodRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindBaseFoodRequest:arg0 arg1: arg1 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(BaseFoodRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[BaseFoodHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:(BaseFoodjsonData*)[__request createObject:__result type:[BaseFoodjsonData class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(BaseFoodjsonData*) findBaseFood:(BaseFoodpageParam*) arg0 arg1:(BaseFoodbaseFood*) arg1 __error:(NSError**) __error 
{
    BaseFoodRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindBaseFoodRequest:arg0 arg1: arg1 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[BaseFoodHelper getResultElement:__request.OutputBody name:@"return"];
    
    NSArray *rows = [__result elementsForName:@"rows"];
    NSMutableArray *foodArray = [[NSMutableArray alloc] init];
    for (DDXMLElement *row in rows){
        id food = [__request createObject:row type:[BaseFoodbaseFood class]];
        [foodArray addObject:food];
    }
    BaseFoodjsonData *foods = (BaseFoodjsonData*)[__request createObject:__result type:[BaseFoodjsonData class]];
    foods.rows = foodArray;
    
    return foods;
}

@end
