//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "BaseFoodjsonData.h"
#import "BaseFoodHelper.h"
#import "BaseFoodfindBaseFoodResponse.h"


@implementation BaseFoodfindBaseFoodResponse
    @synthesize _return;

+ (BaseFoodfindBaseFoodResponse *)createWithXml:(DDXMLElement *)__node __request:(BaseFoodRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(BaseFoodRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([BaseFoodHelper hasValue:__node name:@"return"])
        {
            self._return = (BaseFoodjsonData*)[__request createObject:[BaseFoodHelper getNode:__node name:@"return"] type:[BaseFoodjsonData class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(BaseFoodRequestResultHandler*) __request
{

             
        DDXMLElement* ___returnItemElement=[__request writeElement:_return type:[BaseFoodjsonData class] name:@"return" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___returnItemElement!=nil)
        {
            [self._return serialize:___returnItemElement __request: __request];
        }


}
@end
