//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class BaseFoodpageParam;
@class BaseFoodbaseFood;
#import "BaseFoodRequestResultHandler.h"
#import "DDXML.h"



@interface BaseFoodfindBaseFood : NSObject 


@property (retain,nonatomic,getter=getArg0) BaseFoodpageParam* arg0;

@property (retain,nonatomic,getter=getArg1) BaseFoodbaseFood* arg1;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(BaseFoodRequestResultHandler*) __request;
+(BaseFoodfindBaseFood*) createWithXml:(DDXMLElement*)__node __request:(BaseFoodRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(BaseFoodRequestResultHandler*) __request;
@end