//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "GuideRequestResultHandler.h"
#import "DDXML.h"



@interface Guidesuggestions : NSObject 


@property (retain,nonatomic,getter=getContent) NSString* content;

@property (retain,nonatomic,getter=getCreateTime) NSString* createTime;

@property (retain,nonatomic,getter=getCustomerId) NSString* customerId;

@property (retain,nonatomic,getter=get_id) NSString* _id;

@property (retain,nonatomic,getter=getIsReply) NSString* isReply;

@property (retain,nonatomic,getter=getNickname) NSString* nickname;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(GuideRequestResultHandler*) __request;
+(Guidesuggestions*) createWithXml:(DDXMLElement*)__node __request:(GuideRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(GuideRequestResultHandler*) __request;
@end