//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "GuideHelper.h"
#import "Guidesuggestions.h"


@implementation Guidesuggestions
    @synthesize content;
    @synthesize createTime;
    @synthesize customerId;
    @synthesize _id;
    @synthesize isReply;
    @synthesize nickname;

+ (Guidesuggestions *)createWithXml:(DDXMLElement *)__node __request:(GuideRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(GuideRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([GuideHelper hasValue:__node name:@"content"])
        {
            self.content = [[GuideHelper getNode:__node name:@"content"] stringValue];
        }
        if([GuideHelper hasValue:__node name:@"createTime"])
        {
            self.createTime = [[GuideHelper getNode:__node name:@"createTime"] stringValue];
        }
        if([GuideHelper hasValue:__node name:@"customerId"])
        {
            self.customerId = [[GuideHelper getNode:__node name:@"customerId"] stringValue];
        }
        if([GuideHelper hasValue:__node name:@"id"])
        {
            self._id = [[GuideHelper getNode:__node name:@"id"] stringValue];
        }
        if([GuideHelper hasValue:__node name:@"isReply"])
        {
            self.isReply = [[GuideHelper getNode:__node name:@"isReply"] stringValue];
        }
        if([GuideHelper hasValue:__node name:@"nickname"])
        {
            self.nickname = [[GuideHelper getNode:__node name:@"nickname"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(GuideRequestResultHandler*) __request
{

             
        DDXMLElement* __contentItemElement=[__request writeElement:content type:[NSString class] name:@"content" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__contentItemElement!=nil)
        {
            [__contentItemElement setStringValue:self.content];
        }
             
        DDXMLElement* __createTimeItemElement=[__request writeElement:createTime type:[NSString class] name:@"createTime" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__createTimeItemElement!=nil)
        {
            [__createTimeItemElement setStringValue:self.createTime];
        }
             
        DDXMLElement* __customerIdItemElement=[__request writeElement:customerId type:[NSString class] name:@"customerId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__customerIdItemElement!=nil)
        {
            [__customerIdItemElement setStringValue:self.customerId];
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }
             
        DDXMLElement* __isReplyItemElement=[__request writeElement:isReply type:[NSString class] name:@"isReply" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__isReplyItemElement!=nil)
        {
            [__isReplyItemElement setStringValue:self.isReply];
        }
             
        DDXMLElement* __nicknameItemElement=[__request writeElement:nickname type:[NSString class] name:@"nickname" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__nicknameItemElement!=nil)
        {
            [__nicknameItemElement setStringValue:self.nickname];
        }


}
@end
