//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "AllDicsRequestResultHandler.h"
#import "DDXML.h"



@interface AllDicsdictType : NSObject 


@property (retain,nonatomic,getter=get_id) NSString* _id;

@property (retain,nonatomic,getter=getParentId) NSString* parentId;

@property (retain,nonatomic,getter=getRemark) NSString* remark;

@property (retain,nonatomic,getter=getTypeCode) NSString* typeCode;

@property (retain,nonatomic,getter=getTypeName) NSString* typeName;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(AllDicsRequestResultHandler*) __request;
+(AllDicsdictType*) createWithXml:(DDXMLElement*)__node __request:(AllDicsRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(AllDicsRequestResultHandler*) __request;
@end