//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "AllDicsgetAllDictTypeResponse.h"
#import "DDXML.h"

@class AllDicsRequestResultHandler;

@protocol AllDicsSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface AllDicsDictTypeServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetAllDictTypeRequest:(AllDicsRequestResultHandler*) __request;
-(AllDicsgetAllDictTypeResponse*) getAllDictType:(NSError**) __error;
-(AllDicsRequestResultHandler*) getAllDictTypeAsync:(id) __target __handler:(SEL) __handler;
-(AllDicsRequestResultHandler*) getAllDictTypeAsync:(id<AllDicsSoapServiceResponse>) __target;
-(AllDicsRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(AllDicsRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(AllDicsRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(AllDicsRequestResultHandler*) requestMgr callback:(void (^)(AllDicsRequestResultHandler *)) callback;

@end
