//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "AllDicsDictTypeServiceImplServiceSoapBinding.h"
#import "AllDicsRequestResultHandler.h"
#import "AllDicsHelper.h"

@implementation AllDicsDictTypeServiceImplServiceSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=[NSString stringWithFormat:@"%@%@",WebserviceUrl,@"dictType"];
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(AllDicsRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(AllDicsRequestResultHandler*) CreateRequestResultHandler
{
    return [[AllDicsRequestResultHandler alloc]init];
}
-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(AllDicsRequestResultHandler*) __request
{
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(AllDicsRequestResultHandler*) requestMgr callback:(void (^)(AllDicsRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) creategetAllDictTypeRequest:(AllDicsRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getAllDictType" URI:@"http://service.dict.sys/" parent:__request.Body];
    [self addAdornments:__methodElement];
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(AllDicsRequestResultHandler*) getAllDictTypeAsync:(id) __target __handler:(SEL) __handler
{
    AllDicsRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetAllDictTypeRequest:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(AllDicsRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[AllDicsHelper getResultElement:__request.OutputBody name:@"getAllDictTypeResponse"];
        __res= (AllDicsgetAllDictTypeResponse*)[__request createObject:__result type:[AllDicsgetAllDictTypeResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(AllDicsRequestResultHandler*) getAllDictTypeAsync:(id<AllDicsSoapServiceResponse>) __target
{
    AllDicsRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetAllDictTypeRequest:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(AllDicsRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[AllDicsHelper getResultElement:__request.OutputBody name:@"getAllDictTypeResponse"];
        [__target onSuccess:(AllDicsgetAllDictTypeResponse*)[__request createObject:__result type:[AllDicsgetAllDictTypeResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(AllDicsgetAllDictTypeResponse*) getAllDictType:(NSError**) __error 
{
    AllDicsRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetAllDictTypeRequest:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[AllDicsHelper getResultElement:__request.OutputBody name:@"getAllDictTypeResponse"];
    return (AllDicsgetAllDictTypeResponse*)[__request createObject:__result type:[AllDicsgetAllDictTypeResponse class]];
}

@end
