//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "AllDicsRequestResultHandler.h"
#import "DDXML.h"



@interface AllDicsgetAllDictType : NSObject 

-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(AllDicsRequestResultHandler*) __request;
+(AllDicsgetAllDictType*) createWithXml:(DDXMLElement*)__node __request:(AllDicsRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(AllDicsRequestResultHandler*) __request;
@end