//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "CookBookRequestResultHandler.h"
#import "DDXML.h"



@interface CookBookpageParam : NSObject 


@property (nonatomic,getter=getPage) int page;

@property (nonatomic,getter=getRows) int rows;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(CookBookRequestResultHandler*) __request;
+(CookBookpageParam*) createWithXml:(DDXMLElement*)__node __request:(CookBookRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request;
@end