//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "CookBookcookbook.h"
#import "CookBookjsonData.h"
#import "CookBookpageParam.h"
#import "DDXML.h"

@class CookBookRequestResultHandler;

@protocol CookBookSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface CookBookCookbookServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetByIdRequest:(NSString*) arg0 __request:(CookBookRequestResultHandler*) __request;
-(CookBookcookbook*) getById:(NSString*) arg0 __error:(NSError**) __error;
-(CookBookRequestResultHandler*) getByIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CookBookRequestResultHandler*) getByIdAsync:(NSString*) arg0 __target:(id<CookBookSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfindCookbookByNameRequest:(CookBookpageParam*) arg0 arg1:(NSString*) arg1 __request:(CookBookRequestResultHandler*) __request;
-(CookBookjsonData*) findCookbookByName:(CookBookpageParam*) arg0 arg1:(NSString*) arg1 __error:(NSError**) __error;
-(CookBookRequestResultHandler*) findCookbookByNameAsync:(CookBookpageParam*) arg0 arg1:(NSString*) arg1 __target:(id) __target __handler:(SEL) __handler;
-(CookBookRequestResultHandler*) findCookbookByNameAsync:(CookBookpageParam*) arg0 arg1:(NSString*) arg1 __target:(id<CookBookSoapServiceResponse>) __target;
-(CookBookRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(CookBookRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(CookBookRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(CookBookRequestResultHandler*) requestMgr callback:(void (^)(CookBookRequestResultHandler *)) callback;

@end
