//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CookBookpageParam.h"
#import "CookBookHelper.h"
#import "CookBookfindCookbookByName.h"


@implementation CookBookfindCookbookByName
    @synthesize arg0;
    @synthesize arg1;

+ (CookBookfindCookbookByName *)createWithXml:(DDXMLElement *)__node __request:(CookBookRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CookBookRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CookBookHelper hasValue:__node name:@"arg0"])
        {
            self.arg0 = (CookBookpageParam*)[__request createObject:[CookBookHelper getNode:__node name:@"arg0"] type:[CookBookpageParam class]];
        }
        if([CookBookHelper hasValue:__node name:@"arg1"])
        {
            self.arg1 = [[CookBookHelper getNode:__node name:@"arg1"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request
{

             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[CookBookpageParam class] name:@"arg0" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [self.arg0 serialize:__arg0ItemElement __request: __request];
        }
             
        DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[NSString class] name:@"arg1" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg1ItemElement!=nil)
        {
            [__arg1ItemElement setStringValue:self.arg1];
        }


}
@end
