//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CookBookcookbook.h"
#import "CookBookHelper.h"
#import "CookBookgetByIdResponse.h"


@implementation CookBookgetByIdResponse
    @synthesize _return;

+ (CookBookgetByIdResponse *)createWithXml:(DDXMLElement *)__node __request:(CookBookRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CookBookRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CookBookHelper hasValue:__node name:@"return"])
        {
            self._return = (CookBookcookbook*)[__request createObject:[CookBookHelper getNode:__node name:@"return"] type:[CookBookcookbook class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request
{

             
        DDXMLElement* ___returnItemElement=[__request writeElement:_return type:[CookBookcookbook class] name:@"return" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___returnItemElement!=nil)
        {
            [self._return serialize:___returnItemElement __request: __request];
        }


}
@end
