//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CookBookHelper.h"
#import "CookBookpageParam.h"


@implementation CookBookpageParam
    @synthesize page;
    @synthesize rows;

+ (CookBookpageParam *)createWithXml:(DDXMLElement *)__node __request:(CookBookRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.page =0;
        self.rows =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CookBookRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CookBookHelper hasValue:__node name:@"page"])
        {
            self.page = (int)[[[CookBookHelper getNode:__node name:@"page"] stringValue] integerValue];
        }
        if([CookBookHelper hasValue:__node name:@"rows"])
        {
            self.rows = (int)[[[CookBookHelper getNode:__node name:@"rows"] stringValue] integerValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request
{

             
        DDXMLElement* __pageItemElement=[__request writeElement:@"page" URI:@"" parent:__parent];
        [__pageItemElement setStringValue: [NSString stringWithFormat:@"%i", self.page]];
             
        DDXMLElement* __rowsItemElement=[__request writeElement:@"rows" URI:@"" parent:__parent];
        [__rowsItemElement setStringValue: [NSString stringWithFormat:@"%i", self.rows]];


}
@end
