//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CookBookHelper.h"
#import "CookBookcookbook.h"


@implementation CookBookcookbook
    @synthesize cookbookName;
    @synthesize _id;
    @synthesize image;
    @synthesize jianpin;
    @synthesize url;

+ (CookBookcookbook *)createWithXml:(DDXMLElement *)__node __request:(CookBookRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CookBookRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CookBookHelper hasValue:__node name:@"cookbookName"])
        {
            self.cookbookName = [[CookBookHelper getNode:__node name:@"cookbookName"] stringValue];
        }
        if([CookBookHelper hasValue:__node name:@"id"])
        {
            self._id = [[CookBookHelper getNode:__node name:@"id"] stringValue];
        }
        if([CookBookHelper hasValue:__node name:@"image"])
        {
            self.image = [[CookBookHelper getNode:__node name:@"image"] stringValue];
        }
        if([CookBookHelper hasValue:__node name:@"jianpin"])
        {
            self.jianpin = [[CookBookHelper getNode:__node name:@"jianpin"] stringValue];
        }
        if([CookBookHelper hasValue:__node name:@"url"])
        {
            self.url = [[CookBookHelper getNode:__node name:@"url"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request
{

             
        DDXMLElement* __cookbookNameItemElement=[__request writeElement:cookbookName type:[NSString class] name:@"cookbookName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__cookbookNameItemElement!=nil)
        {
            [__cookbookNameItemElement setStringValue:self.cookbookName];
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }
             
        DDXMLElement* __imageItemElement=[__request writeElement:image type:[NSString class] name:@"image" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__imageItemElement!=nil)
        {
            [__imageItemElement setStringValue:self.image];
        }
             
        DDXMLElement* __jianpinItemElement=[__request writeElement:jianpin type:[NSString class] name:@"jianpin" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__jianpinItemElement!=nil)
        {
            [__jianpinItemElement setStringValue:self.jianpin];
        }
             
        DDXMLElement* __urlItemElement=[__request writeElement:url type:[NSString class] name:@"url" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__urlItemElement!=nil)
        {
            [__urlItemElement setStringValue:self.url];
        }


}
@end
