//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class CookBookpageParam;
#import "CookBookRequestResultHandler.h"
#import "DDXML.h"



@interface CookBookfindCookbookByName : NSObject 


@property (retain,nonatomic,getter=getArg0) CookBookpageParam* arg0;

@property (retain,nonatomic,getter=getArg1) NSString* arg1;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(CookBookRequestResultHandler*) __request;
+(CookBookfindCookbookByName*) createWithXml:(DDXMLElement*)__node __request:(CookBookRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request;
@end