//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class CookBookjsonData;
#import "CookBookRequestResultHandler.h"
#import "DDXML.h"



@interface CookBookfindCookbookByNameResponse : NSObject 


@property (retain,nonatomic,getter=get_return) CookBookjsonData* _return;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(CookBookRequestResultHandler*) __request;
+(CookBookfindCookbookByNameResponse*) createWithXml:(DDXMLElement*)__node __request:(CookBookRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(CookBookRequestResultHandler*) __request;
@end