//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class Customercustomer;
#import "CustomerRequestResultHandler.h"
#import "DDXML.h"



@interface CustomergetCustomerByLoginNameResponse : NSObject 


@property (retain,nonatomic,getter=get_return) Customercustomer* _return;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(CustomerRequestResultHandler*) __request;
+(CustomergetCustomerByLoginNameResponse*) createWithXml:(DDXMLElement*)__node __request:(CustomerRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request;
@end