//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CustomerCustomerServiceImplServiceSoapBinding.h"
#import "CustomerRequestResultHandler.h"
#import "CustomerHelper.h"

@implementation CustomerCustomerServiceImplServiceSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=[NSString stringWithFormat:@"%@%@",WebserviceUrl,@"customer"];
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(CustomerRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(CustomerRequestResultHandler*) CreateRequestResultHandler
{
    return [[CustomerRequestResultHandler alloc]init];
}
-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(CustomerRequestResultHandler*) __request
{
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(CustomerRequestResultHandler*) requestMgr callback:(void (^)(CustomerRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createinsertAllergenRequest:(Customerallergen*) arg0 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"insertAllergen" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[Customerallergen class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [arg0 serialize:__arg0ItemElement __request: __request];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) insertAllergenAsync:(Customerallergen*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createinsertAllergenRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        __res=nil; 
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) insertAllergenAsync:(Customerallergen*) arg0 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createinsertAllergenRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        [__target onSuccess:nil];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(void) insertAllergen:(Customerallergen*) arg0 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createinsertAllergenRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return;
    }
}
-(NSMutableURLRequest*) createfindDietHabitByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"findDietHabitByCustomerId" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [__arg0ItemElement setStringValue:arg0];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) findDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindDietHabitByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"findDietHabitByCustomerIdResponse"];
        __res= (CustomerfindDietHabitByCustomerIdResponse*)[__request createObject:__result type:[CustomerfindDietHabitByCustomerIdResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) findDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindDietHabitByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"findDietHabitByCustomerIdResponse"];
        [__target onSuccess:(CustomerfindDietHabitByCustomerIdResponse*)[__request createObject:__result type:[CustomerfindDietHabitByCustomerIdResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(CustomerfindDietHabitByCustomerIdResponse*) findDietHabitByCustomerId:(NSString*) arg0 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindDietHabitByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"findDietHabitByCustomerIdResponse"];
    return (CustomerfindDietHabitByCustomerIdResponse*)[__request createObject:__result type:[CustomerfindDietHabitByCustomerIdResponse class]];
}
-(NSMutableURLRequest*) createloginRequest:(NSString*) arg0 arg1:(NSString*) arg1 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"login" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [__arg0ItemElement setStringValue:arg0];
        }
             
        DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[NSString class] name:@"arg1" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg1ItemElement!=nil)
        {
            [__arg1ItemElement setStringValue:arg1];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) loginAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createloginRequest:arg0 arg1: arg1 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
        __res= [__result stringValue];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) loginAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createloginRequest:arg0 arg1: arg1 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:[__result stringValue]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(NSString*) login:(NSString*) arg0 arg1:(NSString*) arg1 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createloginRequest:arg0 arg1: arg1 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
    return [__result stringValue];
}
-(NSMutableURLRequest*) createdeleteAllergenByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"deleteAllergenByCustomerId" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [__arg0ItemElement setStringValue:arg0];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) deleteAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createdeleteAllergenByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        __res=nil; 
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) deleteAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createdeleteAllergenByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        [__target onSuccess:nil];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(void) deleteAllergenByCustomerId:(NSString*) arg0 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createdeleteAllergenByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return;
    }
}
-(NSMutableURLRequest*) creategetCustomerByLoginNameRequest:(NSString*) loginName __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getCustomerByLoginName" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __loginNameItemElement=[__request writeElement:loginName type:[NSString class] name:@"loginName" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__loginNameItemElement!=nil)
        {
            [__loginNameItemElement setStringValue:loginName];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) getCustomerByLoginNameAsync:(NSString*) loginName __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetCustomerByLoginNameRequest:loginName __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (Customercustomer*)[__request createObject:__result type:[Customercustomer class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) getCustomerByLoginNameAsync:(NSString*) loginName __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetCustomerByLoginNameRequest:loginName __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:(Customercustomer*)[__request createObject:__result type:[Customercustomer class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(Customercustomer*) getCustomerByLoginName:(NSString*) loginName __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetCustomerByLoginNameRequest:loginName __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
    return (Customercustomer*)[__request createObject:__result type:[Customercustomer class]];
}
-(NSMutableURLRequest*) createinsertDietHabitRequest:(CustomerdietHabit*) arg0 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"insertDietHabit" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[CustomerdietHabit class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [arg0 serialize:__arg0ItemElement __request: __request];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) insertDietHabitAsync:(CustomerdietHabit*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createinsertDietHabitRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        __res=nil; 
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) insertDietHabitAsync:(CustomerdietHabit*) arg0 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createinsertDietHabitRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        [__target onSuccess:nil];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(void) insertDietHabit:(CustomerdietHabit*) arg0 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createinsertDietHabitRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return;
    }
}
-(NSMutableURLRequest*) createfindAllergenByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"findAllergenByCustomerId" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [__arg0ItemElement setStringValue:arg0];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) findAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindAllergenByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"findAllergenByCustomerIdResponse"];
        __res= (CustomerfindAllergenByCustomerIdResponse*)[__request createObject:__result type:[CustomerfindAllergenByCustomerIdResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) findAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindAllergenByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"findAllergenByCustomerIdResponse"];
        [__target onSuccess:(CustomerfindAllergenByCustomerIdResponse*)[__request createObject:__result type:[CustomerfindAllergenByCustomerIdResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(CustomerfindAllergenByCustomerIdResponse*) findAllergenByCustomerId:(NSString*) arg0 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindAllergenByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"findAllergenByCustomerIdResponse"];
    return (CustomerfindAllergenByCustomerIdResponse*)[__request createObject:__result type:[CustomerfindAllergenByCustomerIdResponse class]];
}
-(NSMutableURLRequest*) createsaveCustomerRequest:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"saveCustomer" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[Customercustomer class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [arg0 serialize:__arg0ItemElement __request: __request];
        }
             
        DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[CustomerhealthRecord class] name:@"arg1" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg1ItemElement!=nil)
        {
            [arg1 serialize:__arg1ItemElement __request: __request];
        }
             
        DDXMLElement* __arg2ItemElement=[__request writeElement:arg2 type:[NSString class] name:@"arg2" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg2ItemElement!=nil)
        {
            [__arg2ItemElement setStringValue:arg2];
        }
             
        DDXMLElement* __arg3ItemElement=[__request writeElement:arg3 type:[NSString class] name:@"arg3" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg3ItemElement!=nil)
        {
            [__arg3ItemElement setStringValue:arg3];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) saveCustomerAsync:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsaveCustomerRequest:arg0 arg1: arg1 arg2: arg2 arg3: arg3 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
        __res= [__result stringValue];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) saveCustomerAsync:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsaveCustomerRequest:arg0 arg1: arg1 arg2: arg2 arg3: arg3 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:[__result stringValue]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(NSString*) saveCustomer:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsaveCustomerRequest:arg0 arg1: arg1 arg2: arg2 arg3: arg3 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[CustomerHelper getResultElement:__request.OutputBody name:@"return"];
    return [__result stringValue];
}
-(NSMutableURLRequest*) createdeleteDietHabitByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"deleteDietHabitByCustomerId" URI:@"http://service.customer.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [__arg0ItemElement setStringValue:arg0];
        }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(CustomerRequestResultHandler*) deleteDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createdeleteDietHabitByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        __res=nil; 
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(CustomerRequestResultHandler*) deleteDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createdeleteDietHabitByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(CustomerRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        [__target onSuccess:nil];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(void) deleteDietHabitByCustomerId:(NSString*) arg0 __error:(NSError**) __error 
{
    CustomerRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createdeleteDietHabitByCustomerIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return;
    }
}

@end
