//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "Customercustomer.h"
#import "CustomerHelper.h"
#import "CustomergetCustomerByLoginNameResponse.h"


@implementation CustomergetCustomerByLoginNameResponse
    @synthesize _return;

+ (CustomergetCustomerByLoginNameResponse *)createWithXml:(DDXMLElement *)__node __request:(CustomerRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CustomerRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CustomerHelper hasValue:__node name:@"return"])
        {
            self._return = (Customercustomer*)[__request createObject:[CustomerHelper getNode:__node name:@"return"] type:[Customercustomer class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request
{

             
        DDXMLElement* ___returnItemElement=[__request writeElement:_return type:[Customercustomer class] name:@"return" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___returnItemElement!=nil)
        {
            [self._return serialize:___returnItemElement __request: __request];
        }


}
@end
