//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "CustomerRequestResultHandler.h"
#import "DDXML.h"



@interface CustomerdietHabit : NSObject 


@property (retain,nonatomic,getter=getCustomerId) NSString* customerId;

@property (retain,nonatomic,getter=getDietHabitId) NSString* dietHabitId;

@property (retain,nonatomic,getter=get_id) NSString* _id;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(CustomerRequestResultHandler*) __request;
+(CustomerdietHabit*) createWithXml:(DDXMLElement*)__node __request:(CustomerRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request;
@end