//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

@class Customercustomer;
@class CustomerhealthRecord;
#import "CustomerRequestResultHandler.h"
#import "DDXML.h"



@interface CustomersaveCustomer : NSObject 


@property (retain,nonatomic,getter=getArg0) Customercustomer* arg0;

@property (retain,nonatomic,getter=getArg1) CustomerhealthRecord* arg1;

@property (retain,nonatomic,getter=getArg2) NSString* arg2;

@property (retain,nonatomic,getter=getArg3) NSString* arg3;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(CustomerRequestResultHandler*) __request;
+(CustomersaveCustomer*) createWithXml:(DDXMLElement*)__node __request:(CustomerRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request;
@end