//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "Customercustomer.h"
#import "CustomerhealthRecord.h"
#import "CustomerHelper.h"
#import "CustomersaveCustomer.h"


@implementation CustomersaveCustomer
    @synthesize arg0;
    @synthesize arg1;
    @synthesize arg2;
    @synthesize arg3;

+ (CustomersaveCustomer *)createWithXml:(DDXMLElement *)__node __request:(CustomerRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CustomerRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CustomerHelper hasValue:__node name:@"arg0"])
        {
            self.arg0 = (Customercustomer*)[__request createObject:[CustomerHelper getNode:__node name:@"arg0"] type:[Customercustomer class]];
        }
        if([CustomerHelper hasValue:__node name:@"arg1"])
        {
            self.arg1 = (CustomerhealthRecord*)[__request createObject:[CustomerHelper getNode:__node name:@"arg1"] type:[CustomerhealthRecord class]];
        }
        if([CustomerHelper hasValue:__node name:@"arg2"])
        {
            self.arg2 = [[CustomerHelper getNode:__node name:@"arg2"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"arg3"])
        {
            self.arg3 = [[CustomerHelper getNode:__node name:@"arg3"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request
{

             
        DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[Customercustomer class] name:@"arg0" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg0ItemElement!=nil)
        {
            [self.arg0 serialize:__arg0ItemElement __request: __request];
        }
             
        DDXMLElement* __arg1ItemElement=[__request writeElement:arg1 type:[CustomerhealthRecord class] name:@"arg1" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg1ItemElement!=nil)
        {
            [self.arg1 serialize:__arg1ItemElement __request: __request];
        }
             
        DDXMLElement* __arg2ItemElement=[__request writeElement:arg2 type:[NSString class] name:@"arg2" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg2ItemElement!=nil)
        {
            [__arg2ItemElement setStringValue:self.arg2];
        }
             
        DDXMLElement* __arg3ItemElement=[__request writeElement:arg3 type:[NSString class] name:@"arg3" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__arg3ItemElement!=nil)
        {
            [__arg3ItemElement setStringValue:self.arg3];
        }


}
@end
