//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CustomerHelper.h"
#import "CustomerdietHabit.h"


@implementation CustomerdietHabit
    @synthesize customerId;
    @synthesize dietHabitId;
    @synthesize _id;

+ (CustomerdietHabit *)createWithXml:(DDXMLElement *)__node __request:(CustomerRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CustomerRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CustomerHelper hasValue:__node name:@"customerId"])
        {
            self.customerId = [[CustomerHelper getNode:__node name:@"customerId"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"dietHabitId"])
        {
            self.dietHabitId = [[CustomerHelper getNode:__node name:@"dietHabitId"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"id"])
        {
            self._id = [[CustomerHelper getNode:__node name:@"id"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request
{

             
        DDXMLElement* __customerIdItemElement=[__request writeElement:customerId type:[NSString class] name:@"customerId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__customerIdItemElement!=nil)
        {
            [__customerIdItemElement setStringValue:self.customerId];
        }
             
        DDXMLElement* __dietHabitIdItemElement=[__request writeElement:dietHabitId type:[NSString class] name:@"dietHabitId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__dietHabitIdItemElement!=nil)
        {
            [__dietHabitIdItemElement setStringValue:self.dietHabitId];
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }


}
@end
