//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CustomerHelper.h"
#import "Customercustomer.h"


@implementation Customercustomer
    @synthesize ageGroup;
    @synthesize ageGroupName;
    @synthesize allergen;
    @synthesize areaName;
    @synthesize birthday;
    @synthesize bloodPressure;
    @synthesize bloodType;
    @synthesize bodyMassIndex;
    @synthesize cityId;
    @synthesize constitution;
    @synthesize constitutionName;
    @synthesize customerName;
    @synthesize dietHabit;
    @synthesize education;
    @synthesize email;
    @synthesize ethnic;
    @synthesize ethnicName;
    @synthesize height;
    @synthesize _id;
    @synthesize idNumber;
    @synthesize idType;
    @synthesize loginName;
    @synthesize maritalStatus;
    @synthesize nickname;
    @synthesize password;
    @synthesize phoneNumber;
    @synthesize profession;
    @synthesize province;
    @synthesize provinceId;
    @synthesize sex;
    @synthesize testDate;
    @synthesize weight;

+ (Customercustomer *)createWithXml:(DDXMLElement *)__node __request:(CustomerRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CustomerRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CustomerHelper hasValue:__node name:@"ageGroup"])
        {
            self.ageGroup = [[CustomerHelper getNode:__node name:@"ageGroup"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"ageGroupName"])
        {
            self.ageGroupName = [[CustomerHelper getNode:__node name:@"ageGroupName"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"allergen"])
        {
            self.allergen = [[CustomerHelper getNode:__node name:@"allergen"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"areaName"])
        {
            self.areaName = [[CustomerHelper getNode:__node name:@"areaName"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"birthday"])
        {
            self.birthday = [[CustomerHelper getNode:__node name:@"birthday"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"bloodPressure"])
        {
            self.bloodPressure = [[CustomerHelper getNode:__node name:@"bloodPressure"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"bloodType"])
        {
            self.bloodType = [[CustomerHelper getNode:__node name:@"bloodType"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"bodyMassIndex"])
        {
            self.bodyMassIndex = [[CustomerHelper getNode:__node name:@"bodyMassIndex"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"cityId"])
        {
            self.cityId = [[CustomerHelper getNode:__node name:@"cityId"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"constitution"])
        {
            self.constitution = [[CustomerHelper getNode:__node name:@"constitution"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"constitutionName"])
        {
            self.constitutionName = [[CustomerHelper getNode:__node name:@"constitutionName"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"customerName"])
        {
            self.customerName = [[CustomerHelper getNode:__node name:@"customerName"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"dietHabit"])
        {
            self.dietHabit = [[CustomerHelper getNode:__node name:@"dietHabit"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"education"])
        {
            self.education = [[CustomerHelper getNode:__node name:@"education"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"email"])
        {
            self.email = [[CustomerHelper getNode:__node name:@"email"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"ethnic"])
        {
            self.ethnic = [[CustomerHelper getNode:__node name:@"ethnic"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"ethnicName"])
        {
            self.ethnicName = [[CustomerHelper getNode:__node name:@"ethnicName"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"height"])
        {
            self.height = [[CustomerHelper getNode:__node name:@"height"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"id"])
        {
            self._id = [[CustomerHelper getNode:__node name:@"id"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"idNumber"])
        {
            self.idNumber = [[CustomerHelper getNode:__node name:@"idNumber"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"idType"])
        {
            self.idType = [[CustomerHelper getNode:__node name:@"idType"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"loginName"])
        {
            self.loginName = [[CustomerHelper getNode:__node name:@"loginName"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"maritalStatus"])
        {
            self.maritalStatus = [[CustomerHelper getNode:__node name:@"maritalStatus"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"nickname"])
        {
            self.nickname = [[CustomerHelper getNode:__node name:@"nickname"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"password"])
        {
            self.password = [[CustomerHelper getNode:__node name:@"password"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"phoneNumber"])
        {
            self.phoneNumber = [[CustomerHelper getNode:__node name:@"phoneNumber"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"profession"])
        {
            self.profession = [[CustomerHelper getNode:__node name:@"profession"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"province"])
        {
            self.province = [[CustomerHelper getNode:__node name:@"province"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"provinceId"])
        {
            self.provinceId = [[CustomerHelper getNode:__node name:@"provinceId"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"sex"])
        {
            self.sex = [[CustomerHelper getNode:__node name:@"sex"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"testDate"])
        {
            self.testDate = [[CustomerHelper getNode:__node name:@"testDate"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"weight"])
        {
            self.weight = [[CustomerHelper getNode:__node name:@"weight"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request
{

             
        DDXMLElement* __ageGroupItemElement=[__request writeElement:ageGroup type:[NSString class] name:@"ageGroup" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ageGroupItemElement!=nil)
        {
            [__ageGroupItemElement setStringValue:self.ageGroup];
        }
             
        DDXMLElement* __ageGroupNameItemElement=[__request writeElement:ageGroupName type:[NSString class] name:@"ageGroupName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ageGroupNameItemElement!=nil)
        {
            [__ageGroupNameItemElement setStringValue:self.ageGroupName];
        }
             
        DDXMLElement* __allergenItemElement=[__request writeElement:allergen type:[NSString class] name:@"allergen" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__allergenItemElement!=nil)
        {
            [__allergenItemElement setStringValue:self.allergen];
        }
             
        DDXMLElement* __areaNameItemElement=[__request writeElement:areaName type:[NSString class] name:@"areaName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__areaNameItemElement!=nil)
        {
            [__areaNameItemElement setStringValue:self.areaName];
        }
             
        DDXMLElement* __birthdayItemElement=[__request writeElement:birthday type:[NSString class] name:@"birthday" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__birthdayItemElement!=nil)
        {
            [__birthdayItemElement setStringValue:self.birthday];
        }
             
        DDXMLElement* __bloodPressureItemElement=[__request writeElement:bloodPressure type:[NSString class] name:@"bloodPressure" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__bloodPressureItemElement!=nil)
        {
            [__bloodPressureItemElement setStringValue:self.bloodPressure];
        }
             
        DDXMLElement* __bloodTypeItemElement=[__request writeElement:bloodType type:[NSString class] name:@"bloodType" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__bloodTypeItemElement!=nil)
        {
            [__bloodTypeItemElement setStringValue:self.bloodType];
        }
             
        DDXMLElement* __bodyMassIndexItemElement=[__request writeElement:bodyMassIndex type:[NSString class] name:@"bodyMassIndex" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__bodyMassIndexItemElement!=nil)
        {
            [__bodyMassIndexItemElement setStringValue:self.bodyMassIndex];
        }
             
        DDXMLElement* __cityIdItemElement=[__request writeElement:cityId type:[NSString class] name:@"cityId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__cityIdItemElement!=nil)
        {
            [__cityIdItemElement setStringValue:self.cityId];
        }
             
        DDXMLElement* __constitutionItemElement=[__request writeElement:constitution type:[NSString class] name:@"constitution" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__constitutionItemElement!=nil)
        {
            [__constitutionItemElement setStringValue:self.constitution];
        }
             
        DDXMLElement* __constitutionNameItemElement=[__request writeElement:constitutionName type:[NSString class] name:@"constitutionName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__constitutionNameItemElement!=nil)
        {
            [__constitutionNameItemElement setStringValue:self.constitutionName];
        }
             
        DDXMLElement* __customerNameItemElement=[__request writeElement:customerName type:[NSString class] name:@"customerName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__customerNameItemElement!=nil)
        {
            [__customerNameItemElement setStringValue:self.customerName];
        }
             
        DDXMLElement* __dietHabitItemElement=[__request writeElement:dietHabit type:[NSString class] name:@"dietHabit" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__dietHabitItemElement!=nil)
        {
            [__dietHabitItemElement setStringValue:self.dietHabit];
        }
             
        DDXMLElement* __educationItemElement=[__request writeElement:education type:[NSString class] name:@"education" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__educationItemElement!=nil)
        {
            [__educationItemElement setStringValue:self.education];
        }
             
        DDXMLElement* __emailItemElement=[__request writeElement:email type:[NSString class] name:@"email" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__emailItemElement!=nil)
        {
            [__emailItemElement setStringValue:self.email];
        }
             
        DDXMLElement* __ethnicItemElement=[__request writeElement:ethnic type:[NSString class] name:@"ethnic" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ethnicItemElement!=nil)
        {
            [__ethnicItemElement setStringValue:self.ethnic];
        }
             
        DDXMLElement* __ethnicNameItemElement=[__request writeElement:ethnicName type:[NSString class] name:@"ethnicName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__ethnicNameItemElement!=nil)
        {
            [__ethnicNameItemElement setStringValue:self.ethnicName];
        }
             
        DDXMLElement* __heightItemElement=[__request writeElement:height type:[NSString class] name:@"height" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__heightItemElement!=nil)
        {
            [__heightItemElement setStringValue:self.height];
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }
             
        DDXMLElement* __idNumberItemElement=[__request writeElement:idNumber type:[NSString class] name:@"idNumber" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__idNumberItemElement!=nil)
        {
            [__idNumberItemElement setStringValue:self.idNumber];
        }
             
        DDXMLElement* __idTypeItemElement=[__request writeElement:idType type:[NSString class] name:@"idType" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__idTypeItemElement!=nil)
        {
            [__idTypeItemElement setStringValue:self.idType];
        }
             
        DDXMLElement* __loginNameItemElement=[__request writeElement:loginName type:[NSString class] name:@"loginName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__loginNameItemElement!=nil)
        {
            [__loginNameItemElement setStringValue:self.loginName];
        }
             
        DDXMLElement* __maritalStatusItemElement=[__request writeElement:maritalStatus type:[NSString class] name:@"maritalStatus" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__maritalStatusItemElement!=nil)
        {
            [__maritalStatusItemElement setStringValue:self.maritalStatus];
        }
             
        DDXMLElement* __nicknameItemElement=[__request writeElement:nickname type:[NSString class] name:@"nickname" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__nicknameItemElement!=nil)
        {
            [__nicknameItemElement setStringValue:self.nickname];
        }
             
        DDXMLElement* __passwordItemElement=[__request writeElement:password type:[NSString class] name:@"password" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__passwordItemElement!=nil)
        {
            [__passwordItemElement setStringValue:self.password];
        }
             
        DDXMLElement* __phoneNumberItemElement=[__request writeElement:phoneNumber type:[NSString class] name:@"phoneNumber" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__phoneNumberItemElement!=nil)
        {
            [__phoneNumberItemElement setStringValue:self.phoneNumber];
        }
             
        DDXMLElement* __professionItemElement=[__request writeElement:profession type:[NSString class] name:@"profession" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__professionItemElement!=nil)
        {
            [__professionItemElement setStringValue:self.profession];
        }
             
        DDXMLElement* __provinceItemElement=[__request writeElement:province type:[NSString class] name:@"province" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__provinceItemElement!=nil)
        {
            [__provinceItemElement setStringValue:self.province];
        }
             
        DDXMLElement* __provinceIdItemElement=[__request writeElement:provinceId type:[NSString class] name:@"provinceId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__provinceIdItemElement!=nil)
        {
            [__provinceIdItemElement setStringValue:self.provinceId];
        }
             
        DDXMLElement* __sexItemElement=[__request writeElement:sex type:[NSString class] name:@"sex" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__sexItemElement!=nil)
        {
            [__sexItemElement setStringValue:self.sex];
        }
             
        DDXMLElement* __testDateItemElement=[__request writeElement:testDate type:[NSString class] name:@"testDate" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__testDateItemElement!=nil)
        {
            [__testDateItemElement setStringValue:self.testDate];
        }
             
        DDXMLElement* __weightItemElement=[__request writeElement:weight type:[NSString class] name:@"weight" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__weightItemElement!=nil)
        {
            [__weightItemElement setStringValue:self.weight];
        }


}



+ (Customercustomer*)sharedCustomer
{
    static Customercustomer *_customer = nil;
    
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        _customer = [[self alloc] init];
    });
    
    return _customer;
}

@end
