//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CustomerHelper.h"
#import "CustomergetCustomerByLoginName.h"


@implementation CustomergetCustomerByLoginName
    @synthesize loginName;

+ (CustomergetCustomerByLoginName *)createWithXml:(DDXMLElement *)__node __request:(CustomerRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CustomerRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CustomerHelper hasValue:__node name:@"loginName"])
        {
            self.loginName = [[CustomerHelper getNode:__node name:@"loginName"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request
{

             
        DDXMLElement* __loginNameItemElement=[__request writeElement:loginName type:[NSString class] name:@"loginName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__loginNameItemElement!=nil)
        {
            [__loginNameItemElement setStringValue:self.loginName];
        }


}
@end
