//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "Customerallergen.h"
#import "CustomerfindDietHabitByCustomerIdResponse.h"
#import "Customercustomer.h"
#import "CustomerdietHabit.h"
#import "CustomerfindAllergenByCustomerIdResponse.h"
#import "CustomerhealthRecord.h"
#import "DDXML.h"

@class CustomerRequestResultHandler;

@protocol CustomerSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface CustomerCustomerServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createinsertAllergenRequest:(Customerallergen*) arg0 __request:(CustomerRequestResultHandler*) __request;
-(void) insertAllergen:(Customerallergen*) arg0 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) insertAllergenAsync:(Customerallergen*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) insertAllergenAsync:(Customerallergen*) arg0 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfindDietHabitByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request;
-(CustomerfindDietHabitByCustomerIdResponse*) findDietHabitByCustomerId:(NSString*) arg0 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) findDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) findDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createloginRequest:(NSString*) arg0 arg1:(NSString*) arg1 __request:(CustomerRequestResultHandler*) __request;
-(NSString*) login:(NSString*) arg0 arg1:(NSString*) arg1 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) loginAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) loginAsync:(NSString*) arg0 arg1:(NSString*) arg1 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createdeleteAllergenByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request;
-(void) deleteAllergenByCustomerId:(NSString*) arg0 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) deleteAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) deleteAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetCustomerByLoginNameRequest:(NSString*) loginName __request:(CustomerRequestResultHandler*) __request;
-(Customercustomer*) getCustomerByLoginName:(NSString*) loginName __error:(NSError**) __error;
-(CustomerRequestResultHandler*) getCustomerByLoginNameAsync:(NSString*) loginName __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) getCustomerByLoginNameAsync:(NSString*) loginName __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createinsertDietHabitRequest:(CustomerdietHabit*) arg0 __request:(CustomerRequestResultHandler*) __request;
-(void) insertDietHabit:(CustomerdietHabit*) arg0 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) insertDietHabitAsync:(CustomerdietHabit*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) insertDietHabitAsync:(CustomerdietHabit*) arg0 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfindAllergenByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request;
-(CustomerfindAllergenByCustomerIdResponse*) findAllergenByCustomerId:(NSString*) arg0 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) findAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) findAllergenByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createsaveCustomerRequest:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __request:(CustomerRequestResultHandler*) __request;
-(NSString*) saveCustomer:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) saveCustomerAsync:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) saveCustomerAsync:(Customercustomer*) arg0 arg1:(CustomerhealthRecord*) arg1 arg2:(NSString*) arg2 arg3:(NSString*) arg3 __target:(id<CustomerSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createdeleteDietHabitByCustomerIdRequest:(NSString*) arg0 __request:(CustomerRequestResultHandler*) __request;
-(void) deleteDietHabitByCustomerId:(NSString*) arg0 __error:(NSError**) __error;
-(CustomerRequestResultHandler*) deleteDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(CustomerRequestResultHandler*) deleteDietHabitByCustomerIdAsync:(NSString*) arg0 __target:(id<CustomerSoapServiceResponse>) __target;
-(CustomerRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(CustomerRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(CustomerRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(CustomerRequestResultHandler*) requestMgr callback:(void (^)(CustomerRequestResultHandler *)) callback;

@end
