//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "CustomerHelper.h"
#import "Customerallergen.h"


@implementation Customerallergen
    @synthesize allergenId;
    @synthesize customerId;
    @synthesize _id;

+ (Customerallergen *)createWithXml:(DDXMLElement *)__node __request:(CustomerRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(CustomerRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([CustomerHelper hasValue:__node name:@"allergenId"])
        {
            self.allergenId = [[CustomerHelper getNode:__node name:@"allergenId"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"customerId"])
        {
            self.customerId = [[CustomerHelper getNode:__node name:@"customerId"] stringValue];
        }
        if([CustomerHelper hasValue:__node name:@"id"])
        {
            self._id = [[CustomerHelper getNode:__node name:@"id"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(CustomerRequestResultHandler*) __request
{

             
        DDXMLElement* __allergenIdItemElement=[__request writeElement:allergenId type:[NSString class] name:@"allergenId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__allergenIdItemElement!=nil)
        {
            [__allergenIdItemElement setStringValue:self.allergenId];
        }
             
        DDXMLElement* __customerIdItemElement=[__request writeElement:customerId type:[NSString class] name:@"customerId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__customerIdItemElement!=nil)
        {
            [__customerIdItemElement setStringValue:self.customerId];
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }


}
@end
