//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "DicRequestResultHandler.h"
#import "DDXML.h"



@interface Dicdict : NSObject 


@property (retain,nonatomic,getter=getDictCode) NSString* dictCode;

@property (retain,nonatomic,getter=getDictName) NSString* dictName;

@property (retain,nonatomic,getter=get_id) NSString* _id;

@property (retain,nonatomic,getter=getNameJianpin) NSString* nameJianpin;

@property (retain,nonatomic,getter=getNamePinyin) NSString* namePinyin;

@property (nonatomic,getter=getOrderNo) int orderNo;

@property (retain,nonatomic,getter=getRemark) NSString* remark;

@property (retain,nonatomic,getter=getTypeId) NSString* typeId;


-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(DicRequestResultHandler*) __request;
+(Dicdict*) createWithXml:(DDXMLElement*)__node __request:(DicRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(DicRequestResultHandler*) __request;
@end