//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "DicHelper.h"
#import "Dicdict.h"


@implementation Dicdict
    @synthesize dictCode;
    @synthesize dictName;
    @synthesize _id;
    @synthesize nameJianpin;
    @synthesize namePinyin;
    @synthesize orderNo;
    @synthesize remark;
    @synthesize typeId;

+ (Dicdict *)createWithXml:(DDXMLElement *)__node __request:(DicRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.orderNo =0;
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(DicRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([DicHelper hasValue:__node name:@"dictCode"])
        {
            self.dictCode = [[DicHelper getNode:__node name:@"dictCode"] stringValue];
        }
        if([DicHelper hasValue:__node name:@"dictName"])
        {
            self.dictName = [[DicHelper getNode:__node name:@"dictName"] stringValue];
        }
        if([DicHelper hasValue:__node name:@"id"])
        {
            self._id = [[DicHelper getNode:__node name:@"id"] stringValue];
        }
        if([DicHelper hasValue:__node name:@"nameJianpin"])
        {
            self.nameJianpin = [[DicHelper getNode:__node name:@"nameJianpin"] stringValue];
        }
        if([DicHelper hasValue:__node name:@"namePinyin"])
        {
            self.namePinyin = [[DicHelper getNode:__node name:@"namePinyin"] stringValue];
        }
        if([DicHelper hasValue:__node name:@"orderNo"])
        {
            self.orderNo = (int)[[[DicHelper getNode:__node name:@"orderNo"] stringValue] integerValue];
        }
        if([DicHelper hasValue:__node name:@"remark"])
        {
            self.remark = [[DicHelper getNode:__node name:@"remark"] stringValue];
        }
        if([DicHelper hasValue:__node name:@"typeId"])
        {
            self.typeId = [[DicHelper getNode:__node name:@"typeId"] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(DicRequestResultHandler*) __request
{

             
        DDXMLElement* __dictCodeItemElement=[__request writeElement:dictCode type:[NSString class] name:@"dictCode" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__dictCodeItemElement!=nil)
        {
            [__dictCodeItemElement setStringValue:self.dictCode];
        }
             
        DDXMLElement* __dictNameItemElement=[__request writeElement:dictName type:[NSString class] name:@"dictName" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__dictNameItemElement!=nil)
        {
            [__dictNameItemElement setStringValue:self.dictName];
        }
             
        DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___idItemElement!=nil)
        {
            [___idItemElement setStringValue:self._id];
        }
             
        DDXMLElement* __nameJianpinItemElement=[__request writeElement:nameJianpin type:[NSString class] name:@"nameJianpin" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__nameJianpinItemElement!=nil)
        {
            [__nameJianpinItemElement setStringValue:self.nameJianpin];
        }
             
        DDXMLElement* __namePinyinItemElement=[__request writeElement:namePinyin type:[NSString class] name:@"namePinyin" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__namePinyinItemElement!=nil)
        {
            [__namePinyinItemElement setStringValue:self.namePinyin];
        }
             
        DDXMLElement* __orderNoItemElement=[__request writeElement:@"orderNo" URI:@"" parent:__parent];
        [__orderNoItemElement setStringValue: [NSString stringWithFormat:@"%i", self.orderNo]];
             
        DDXMLElement* __remarkItemElement=[__request writeElement:remark type:[NSString class] name:@"remark" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__remarkItemElement!=nil)
        {
            [__remarkItemElement setStringValue:self.remark];
        }
             
        DDXMLElement* __typeIdItemElement=[__request writeElement:typeId type:[NSString class] name:@"typeId" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(__typeIdItemElement!=nil)
        {
            [__typeIdItemElement setStringValue:self.typeId];
        }


}
@end
