//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "Dicdict.h"
#import "DicgetDictByTypeIdResponse.h"
#import "DicgetDictByTypeCodeResponse.h"
#import "DDXML.h"

@class DicRequestResultHandler;

@protocol DicSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface DicDictServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetDictByIdRequest:(NSString*) arg0 __request:(DicRequestResultHandler*) __request;
-(Dicdict*) getDictById:(NSString*) arg0 __error:(NSError**) __error;
-(DicRequestResultHandler*) getDictByIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(DicRequestResultHandler*) getDictByIdAsync:(NSString*) arg0 __target:(id<DicSoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetDictByTypeIdRequest:(NSString*) arg0 __request:(DicRequestResultHandler*) __request;
-(DicgetDictByTypeIdResponse*) getDictByTypeId:(NSString*) arg0 __error:(NSError**) __error;
-(DicRequestResultHandler*) getDictByTypeIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(DicRequestResultHandler*) getDictByTypeIdAsync:(NSString*) arg0 __target:(id<DicSoapServiceResponse>) __target;
-(NSMutableURLRequest*) creategetDictByTypeCodeRequest:(NSString*) arg0 __request:(DicRequestResultHandler*) __request;
-(DicgetDictByTypeCodeResponse*) getDictByTypeCode:(NSString*) arg0 __error:(NSError**) __error;
-(DicRequestResultHandler*) getDictByTypeCodeAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(DicRequestResultHandler*) getDictByTypeCodeAsync:(NSString*) arg0 __target:(id<DicSoapServiceResponse>) __target;
-(DicRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(DicRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(DicRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(DicRequestResultHandler*) requestMgr callback:(void (^)(DicRequestResultHandler *)) callback;

@end
