//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.1.0
//
// Created by Quasar Development at 29-03-2014
//
//---------------------------------------------------


#import "Dicdict.h"
#import "DicHelper.h"
#import "DicgetDictByIdResponse.h"


@implementation DicgetDictByIdResponse
    @synthesize _return;

+ (DicgetDictByIdResponse *)createWithXml:(DDXMLElement *)__node __request:(DicRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(DicRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([DicHelper hasValue:__node name:@"return"])
        {
            self._return = (Dicdict*)[__request createObject:[DicHelper getNode:__node name:@"return"] type:[Dicdict class]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(DicRequestResultHandler*) __request
{

             
        DDXMLElement* ___returnItemElement=[__request writeElement:_return type:[Dicdict class] name:@"return" URI:@"" parent:__parent skipNullProperty:__request.SkipNullProperties];
        if(___returnItemElement!=nil)
        {
            [self._return serialize:___returnItemElement __request: __request];
        }


}
@end
