//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.2
//
// Created by Quasar Development at 09-06-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "GLGfindResponse.h"
#import "GLGsuggestions.h"
#import "DDXML.h"

@class GLGRequestResultHandler;

@protocol GLGSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface GLGSuggestionsServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) createfindRequest:(GLGsuggestions*) arg0 __request:(GLGRequestResultHandler*) __request;
-(GLGfindResponse*) find:(GLGsuggestions*) arg0 __error:(NSError**) __error;
-(GLGRequestResultHandler*) findAsync:(GLGsuggestions*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(GLGRequestResultHandler*) findAsync:(GLGsuggestions*) arg0 __target:(id<GLGSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createsaveRequest:(GLGsuggestions*) arg0 __request:(GLGRequestResultHandler*) __request;
-(void) save:(GLGsuggestions*) arg0 __error:(NSError**) __error;
-(GLGRequestResultHandler*) saveAsync:(GLGsuggestions*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(GLGRequestResultHandler*) saveAsync:(GLGsuggestions*) arg0 __target:(id<GLGSoapServiceResponse>) __target;
-(NSString*) getReplyBySuggestId:(NSString*) arg0 __error:(NSError**) __error;
-(GLGRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(GLGRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id<GLGSoapServiceResponse>) __target;
-(GLGRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(GLGRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(GLGRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(GLGRequestResultHandler*) requestMgr callback:(void (^)(GLGRequestResultHandler *)) callback;

@end
