//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.2
//
// Created by Quasar Development at 09-06-2014
//
//---------------------------------------------------


#import "GLGSuggestionsServiceImplServiceSoapBinding.h"
#import "GLGRequestResultHandler.h"
#import "GLGHelper.h"

@implementation GLGSuggestionsServiceImplServiceSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=[NSString stringWithFormat:@"%@%@",WebserviceUrl,@"suggestions"];
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(GLGRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(GLGRequestResultHandler*) CreateRequestResultHandler
{
    return [[GLGRequestResultHandler alloc]init];
}
-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(GLGRequestResultHandler*) __request
{
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(GLGRequestResultHandler*) requestMgr callback:(void (^)(GLGRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) createfindRequest:(GLGsuggestions*) arg0 __request:(GLGRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"find" URI:@"http://service.suggestions.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[GLGsuggestions class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:YES];
    if(__arg0ItemElement!=nil)
    {
        [arg0 serialize:__arg0ItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(GLGRequestResultHandler*) findAsync:(GLGsuggestions*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    GLGRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(GLGRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[GLGHelper getResultElement:__request.OutputBody name:@"findResponse"];
        __res= (GLGfindResponse*)[__request createObject:__result type:[GLGfindResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(GLGRequestResultHandler*) findAsync:(GLGsuggestions*) arg0 __target:(id<GLGSoapServiceResponse>) __target
{
    GLGRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(GLGRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[GLGHelper getResultElement:__request.OutputBody name:@"findResponse"];
        [__target onSuccess:(GLGfindResponse*)[__request createObject:__result type:[GLGfindResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(GLGfindResponse*) find:(GLGsuggestions*) arg0 __error:(NSError**) __error 
{
    GLGRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[GLGHelper getResultElement:__request.OutputBody name:@"findResponse"];
    return (GLGfindResponse*)[__request createObject:__result type:[GLGfindResponse class]];
}
-(NSMutableURLRequest*) createsaveRequest:(GLGsuggestions*) arg0 __request:(GLGRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"save" URI:@"http://service.suggestions.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[GLGsuggestions class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:YES];
    if(__arg0ItemElement!=nil)
    {
        [arg0 serialize:__arg0ItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(GLGRequestResultHandler*) saveAsync:(GLGsuggestions*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    GLGRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsaveRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(GLGRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        __res=nil; 
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(GLGRequestResultHandler*) saveAsync:(GLGsuggestions*) arg0 __target:(id<GLGSoapServiceResponse>) __target
{
    GLGRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsaveRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(GLGRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        [__target onSuccess:nil];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(void) save:(GLGsuggestions*) arg0 __error:(NSError**) __error 
{
    GLGRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createsaveRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return;
    }
}

-(GLGRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(GLGRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id<GLGSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(NSString*) getReplyBySuggestId:(NSString*) arg0 __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

@end
