//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 17-10-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "HFNRequestResultHandler.h"
#import "DDXML.h"



@interface HFNdietaryAdvice : NSObject 


@property (retain,nonatomic,getter=getArea) NSString* area;

@property (retain,nonatomic,getter=getAreaName) NSString* areaName;

@property (retain,nonatomic,getter=getBreakfast) NSString* breakfast;

@property (retain,nonatomic,getter=getCityId) NSString* cityId;

@property (retain,nonatomic,getter=getConstitution) NSString* constitution;

@property (retain,nonatomic,getter=getConstitutionName) NSString* constitutionName;

@property (retain,nonatomic,getter=getCookbookDate) NSString* cookbookDate;

@property (retain,nonatomic,getter=getCreateUserId) NSString* createUserId;

@property (retain,nonatomic,getter=getFruit) NSString* fruit;

@property (retain,nonatomic,getter=get_id) NSString* _id;

@property (retain,nonatomic,getter=getLunch) NSString* lunch;

@property (retain,nonatomic,getter=getProvinceId) NSString* provinceId;

@property (retain,nonatomic,getter=getStatus) NSString* status;

@property (retain,nonatomic,getter=getSuitable) NSString* suitable;

@property (retain,nonatomic,getter=getSupper) NSString* supper;

@property (retain,nonatomic,getter=getTaboo) NSString* taboo;

@property (retain,nonatomic,getter=getTea) NSString* tea;

@property (retain,nonatomic,getter=getWeather) NSString* weather;

@property (retain,nonatomic,getter=getYs) NSString* ys;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(HFNRequestResultHandler*) __request;
+(HFNdietaryAdvice*) createWithXml:(DDXMLElement*)__node __request:(HFNRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(HFNRequestResultHandler*) __request;
@end