//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 17-10-2014
//
//---------------------------------------------------


#import "HFNHelper.h"
#import "HFNdietaryAdvice.h"


@implementation HFNdietaryAdvice
@synthesize area;
@synthesize areaName;
@synthesize breakfast;
@synthesize cityId;
@synthesize constitution;
@synthesize constitutionName;
@synthesize cookbookDate;
@synthesize createUserId;
@synthesize fruit;
@synthesize _id;
@synthesize lunch;
@synthesize provinceId;
@synthesize status;
@synthesize suitable;
@synthesize supper;
@synthesize taboo;
@synthesize tea;
@synthesize weather;
@synthesize ys;

+ (HFNdietaryAdvice *)createWithXml:(DDXMLElement *)__node __request:(HFNRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(HFNRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([HFNHelper hasValue:__node name:@"area" index:0])
        {
            self.area = [[HFNHelper getNode:__node name:@"area" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"areaName" index:0])
        {
            self.areaName = [[HFNHelper getNode:__node name:@"areaName" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"breakfast" index:0])
        {
            self.breakfast = [[HFNHelper getNode:__node name:@"breakfast" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"cityId" index:0])
        {
            self.cityId = [[HFNHelper getNode:__node name:@"cityId" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"constitution" index:0])
        {
            self.constitution = [[HFNHelper getNode:__node name:@"constitution" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"constitutionName" index:0])
        {
            self.constitutionName = [[HFNHelper getNode:__node name:@"constitutionName" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"cookbookDate" index:0])
        {
            self.cookbookDate = [[HFNHelper getNode:__node name:@"cookbookDate" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"createUserId" index:0])
        {
            self.createUserId = [[HFNHelper getNode:__node name:@"createUserId" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"fruit" index:0])
        {
            self.fruit = [[HFNHelper getNode:__node name:@"fruit" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"id" index:0])
        {
            self._id = [[HFNHelper getNode:__node name:@"id" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"lunch" index:0])
        {
            self.lunch = [[HFNHelper getNode:__node name:@"lunch" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"provinceId" index:0])
        {
            self.provinceId = [[HFNHelper getNode:__node name:@"provinceId" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"status" index:0])
        {
            self.status = [[HFNHelper getNode:__node name:@"status" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"suitable" index:0])
        {
            self.suitable = [[HFNHelper getNode:__node name:@"suitable" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"supper" index:0])
        {
            self.supper = [[HFNHelper getNode:__node name:@"supper" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"taboo" index:0])
        {
            self.taboo = [[HFNHelper getNode:__node name:@"taboo" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"tea" index:0])
        {
            self.tea = [[HFNHelper getNode:__node name:@"tea" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"weather" index:0])
        {
            self.weather = [[HFNHelper getNode:__node name:@"weather" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"ys" index:0])
        {
            self.ys = [[HFNHelper getNode:__node name:@"ys" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(HFNRequestResultHandler*) __request
{

             
    DDXMLElement* __areaItemElement=[__request writeElement:area type:[NSString class] name:@"area" URI:@"" parent:__parent skipNullProperty:YES];
    if(__areaItemElement!=nil)
    {
        [__areaItemElement setStringValue:self.area];
    }
             
    DDXMLElement* __areaNameItemElement=[__request writeElement:areaName type:[NSString class] name:@"areaName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__areaNameItemElement!=nil)
    {
        [__areaNameItemElement setStringValue:self.areaName];
    }
             
    DDXMLElement* __breakfastItemElement=[__request writeElement:breakfast type:[NSString class] name:@"breakfast" URI:@"" parent:__parent skipNullProperty:YES];
    if(__breakfastItemElement!=nil)
    {
        [__breakfastItemElement setStringValue:self.breakfast];
    }
             
    DDXMLElement* __cityIdItemElement=[__request writeElement:cityId type:[NSString class] name:@"cityId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__cityIdItemElement!=nil)
    {
        [__cityIdItemElement setStringValue:self.cityId];
    }
             
    DDXMLElement* __constitutionItemElement=[__request writeElement:constitution type:[NSString class] name:@"constitution" URI:@"" parent:__parent skipNullProperty:YES];
    if(__constitutionItemElement!=nil)
    {
        [__constitutionItemElement setStringValue:self.constitution];
    }
             
    DDXMLElement* __constitutionNameItemElement=[__request writeElement:constitutionName type:[NSString class] name:@"constitutionName" URI:@"" parent:__parent skipNullProperty:YES];
    if(__constitutionNameItemElement!=nil)
    {
        [__constitutionNameItemElement setStringValue:self.constitutionName];
    }
             
    DDXMLElement* __cookbookDateItemElement=[__request writeElement:cookbookDate type:[NSString class] name:@"cookbookDate" URI:@"" parent:__parent skipNullProperty:YES];
    if(__cookbookDateItemElement!=nil)
    {
        [__cookbookDateItemElement setStringValue:self.cookbookDate];
    }
             
    DDXMLElement* __createUserIdItemElement=[__request writeElement:createUserId type:[NSString class] name:@"createUserId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__createUserIdItemElement!=nil)
    {
        [__createUserIdItemElement setStringValue:self.createUserId];
    }
             
    DDXMLElement* __fruitItemElement=[__request writeElement:fruit type:[NSString class] name:@"fruit" URI:@"" parent:__parent skipNullProperty:YES];
    if(__fruitItemElement!=nil)
    {
        [__fruitItemElement setStringValue:self.fruit];
    }
             
    DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:YES];
    if(___idItemElement!=nil)
    {
        [___idItemElement setStringValue:self._id];
    }
             
    DDXMLElement* __lunchItemElement=[__request writeElement:lunch type:[NSString class] name:@"lunch" URI:@"" parent:__parent skipNullProperty:YES];
    if(__lunchItemElement!=nil)
    {
        [__lunchItemElement setStringValue:self.lunch];
    }
             
    DDXMLElement* __provinceIdItemElement=[__request writeElement:provinceId type:[NSString class] name:@"provinceId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__provinceIdItemElement!=nil)
    {
        [__provinceIdItemElement setStringValue:self.provinceId];
    }
             
    DDXMLElement* __statusItemElement=[__request writeElement:status type:[NSString class] name:@"status" URI:@"" parent:__parent skipNullProperty:YES];
    if(__statusItemElement!=nil)
    {
        [__statusItemElement setStringValue:self.status];
    }
             
    DDXMLElement* __suitableItemElement=[__request writeElement:suitable type:[NSString class] name:@"suitable" URI:@"" parent:__parent skipNullProperty:YES];
    if(__suitableItemElement!=nil)
    {
        [__suitableItemElement setStringValue:self.suitable];
    }
             
    DDXMLElement* __supperItemElement=[__request writeElement:supper type:[NSString class] name:@"supper" URI:@"" parent:__parent skipNullProperty:YES];
    if(__supperItemElement!=nil)
    {
        [__supperItemElement setStringValue:self.supper];
    }
             
    DDXMLElement* __tabooItemElement=[__request writeElement:taboo type:[NSString class] name:@"taboo" URI:@"" parent:__parent skipNullProperty:YES];
    if(__tabooItemElement!=nil)
    {
        [__tabooItemElement setStringValue:self.taboo];
    }
             
    DDXMLElement* __teaItemElement=[__request writeElement:tea type:[NSString class] name:@"tea" URI:@"" parent:__parent skipNullProperty:YES];
    if(__teaItemElement!=nil)
    {
        [__teaItemElement setStringValue:self.tea];
    }
             
    DDXMLElement* __weatherItemElement=[__request writeElement:weather type:[NSString class] name:@"weather" URI:@"" parent:__parent skipNullProperty:YES];
    if(__weatherItemElement!=nil)
    {
        [__weatherItemElement setStringValue:self.weather];
    }
             
    DDXMLElement* __ysItemElement=[__request writeElement:ys type:[NSString class] name:@"ys" URI:@"" parent:__parent skipNullProperty:YES];
    if(__ysItemElement!=nil)
    {
        [__ysItemElement setStringValue:self.ys];
    }


}
@end
