//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 17-10-2014
//
//---------------------------------------------------


#import "HFNHelper.h"
#import "HFNjsonData.h"


@implementation HFNjsonData
@synthesize errorTrace;
@synthesize extData;
@synthesize msg;
@synthesize rows;
@synthesize success;
@synthesize total;

+ (HFNjsonData *)createWithXml:(DDXMLElement *)__node __request:(HFNRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
        self.rows =[NSMutableArray array];
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(HFNRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([HFNHelper hasValue:__node name:@"errorTrace" index:0])
        {
            self.errorTrace = [[HFNHelper getNode:__node name:@"errorTrace" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"extData" index:0])
        {
            self.extData = [[HFNHelper getNode:__node name:@"extData" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"msg" index:0])
        {
            self.msg = [[HFNHelper getNode:__node name:@"msg" index:0] stringValue];
        }
        if([HFNHelper hasValue:__node name:@"rows"])
        {
            NSArray* __items=[__node elementsForName:@"rows"];
            for (DDXMLElement* __item in __items) {
                [self.rows addObject:[__item stringValue]];
            }
        }
        if([HFNHelper hasValue:__node name:@"success" index:0])
        {
            self.success = [[[HFNHelper getNode:__node name:@"success" index:0] stringValue] boolValue];
        }
        if([HFNHelper hasValue:__node name:@"total" index:0])
        {
            self.total = [NSNumber numberWithInt:[[[HFNHelper getNode:__node name:@"total" index:0] stringValue] intValue]];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(HFNRequestResultHandler*) __request
{

             
    DDXMLElement* __errorTraceItemElement=[__request writeElement:errorTrace type:[NSString class] name:@"errorTrace" URI:@"" parent:__parent skipNullProperty:YES];
    if(__errorTraceItemElement!=nil)
    {
        [__errorTraceItemElement setStringValue:self.errorTrace];
    }
             
    DDXMLElement* __extDataItemElement=[__request writeElement:extData type:[NSString class] name:@"extData" URI:@"" parent:__parent skipNullProperty:YES];
    if(__extDataItemElement!=nil)
    {
        [__extDataItemElement setStringValue:self.extData];
    }
             
    DDXMLElement* __msgItemElement=[__request writeElement:msg type:[NSString class] name:@"msg" URI:@"" parent:__parent skipNullProperty:YES];
    if(__msgItemElement!=nil)
    {
        [__msgItemElement setStringValue:self.msg];
    }
             
    if(self.rows!=nil)
    {
        for (NSString* __item in self.rows) {
            DDXMLElement* __rowsItemElement=[__request writeElement:rows type:[NSString class] name:@"rows" URI:@"" parent:__parent skipNullProperty:NO];
            if(__rowsItemElement!=nil)
            {
                [__rowsItemElement setStringValue:__item];
            }
        }
    }
             
    DDXMLElement* __successItemElement=[__request writeElement:@"success" URI:@"" parent:__parent];
    [__successItemElement setStringValue:[HFNHelper toBoolStringFromBool:self.success]];
             
    DDXMLElement* __totalItemElement=[__request writeElement:total type:[NSNumber class] name:@"total" URI:@"" parent:__parent skipNullProperty:YES];
    if(__totalItemElement!=nil)
    {
        [__totalItemElement setStringValue:[self.total stringValue]];
    }


}
@end
