//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 17-10-2014
//
//---------------------------------------------------


#import <Foundation/Foundation.h>

#import "HFNRequestResultHandler.h"
#import "DDXML.h"



@interface HFNjsonData : NSObject 


@property (retain,nonatomic,getter=getErrorTrace) NSString* errorTrace;

@property (retain,nonatomic,getter=getExtData) NSString* extData;

@property (retain,nonatomic,getter=getMsg) NSString* msg;

@property (retain,nonatomic,getter=getRows) NSMutableArray* rows;

@property (nonatomic,getter=getSuccess) BOOL success;

@property (retain,nonatomic,getter=getTotal) NSNumber* total;
-(id)init;
-(id)initWithXml: (DDXMLElement*)__node __request:(HFNRequestResultHandler*) __request;
+(HFNjsonData*) createWithXml:(DDXMLElement*)__node __request:(HFNRequestResultHandler*) __request;
-(void) serialize:(DDXMLElement*)__parent __request:(HFNRequestResultHandler*) __request;
@end