//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 4.0.4.1
//
// Created by Quasar Development at 17-10-2014
//
//---------------------------------------------------


#import "HFNSoapError.h"

@implementation HFNSoapError
@synthesize Details;

-(id)initWithDetails:(NSString*) faultString details:(id)details
{
    if(self = [self initWithDomain:faultString code:0 userInfo:nil])
    {
        self.Details=details;
    }
    return self;
}
@end