//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.2
//
// Created by Quasar Development at 11-06-2014
//
//---------------------------------------------------


#import "KGFSuggestionsServiceImplServiceSoapBinding.h"
#import "KGFRequestResultHandler.h"
#import "KGFHelper.h"

@implementation KGFSuggestionsServiceImplServiceSoapBinding
@synthesize Url,ShouldAddAdornments,Headers;

- (id) init {
    if(self = [super init])
    {
        self.Url=[NSString stringWithFormat:@"%@%@",WebserviceUrl,@"suggestions"];
        self.ShouldAddAdornments=YES;
    }
    return self;
}

- (id) initWithUrl: (NSString*) url {
    if(self = [self init])
    {
        self.Url=url;
    }
    return self;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(KGFRequestResultHandler*) requestMgr
{
    [requestMgr sendImplementation:request];
}

-(KGFRequestResultHandler*) CreateRequestResultHandler
{
    return [[KGFRequestResultHandler alloc]init];
}
-(NSMutableURLRequest*) createRequest:(NSString *)__soapAction __request:(KGFRequestResultHandler*) __request
{
    NSString *__soapMessage=[__request getEnvelopeString];
    NSURL *__url = [NSURL URLWithString:Url];
    NSMutableURLRequest *__requestObj = [NSMutableURLRequest requestWithURL:__url];
    NSString *msgLength = [NSString stringWithFormat:@"%lu", (unsigned long)[__soapMessage length]];

    [__requestObj addValue: @"text/xml; charset=utf-8" forHTTPHeaderField:@"Content-Type"];
    [__requestObj addValue: __soapAction forHTTPHeaderField:@"SOAPAction"];
    [__requestObj addValue: msgLength forHTTPHeaderField:@"Content-Length"];
    for (NSString* key in self.Headers) {
        [__requestObj addValue: [self.Headers objectForKey:key] forHTTPHeaderField:key];
    }
    [__requestObj setHTTPMethod:@"POST"];
    [__requestObj setHTTPBody: [__soapMessage dataUsingEncoding:NSUTF8StringEncoding]];
    return __requestObj;
}

-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(KGFRequestResultHandler*) requestMgr callback:(void (^)(KGFRequestResultHandler *)) callback
{
    [requestMgr sendImplementation:request callbackDelegate:callback];
}

-(void) addAdornments:(DDXMLElement*)__methodElement
{
    if(ShouldAddAdornments)
    {
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"id" stringValue:@"o0"]];
        [__methodElement addAttribute:[DDXMLNode attributeWithName:@"c:root" stringValue:@"1"]];
    }
}

-(NSMutableURLRequest*) creategetReplyBySuggestIdRequest:(NSString*) arg0 __request:(KGFRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"getReplyBySuggestId" URI:@"http://service.suggestions.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[NSString class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:YES];
    if(__arg0ItemElement!=nil)
    {
        [__arg0ItemElement setStringValue:arg0];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(KGFRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    KGFRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetReplyBySuggestIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(KGFRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[KGFHelper getResultElement:__request.OutputBody name:@"return"];
        __res= (KGFsuggestionsReply*)[__request createObject:__result type:[KGFsuggestionsReply class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(KGFRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id<KGFSoapServiceResponse>) __target
{
    KGFRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetReplyBySuggestIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(KGFRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[KGFHelper getResultElement:__request.OutputBody name:@"return"];
        [__target onSuccess:(KGFsuggestionsReply*)[__request createObject:__result type:[KGFsuggestionsReply class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(KGFsuggestionsReply*) getReplyBySuggestId:(NSString*) arg0 __error:(NSError**) __error 
{
    KGFRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self creategetReplyBySuggestIdRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[KGFHelper getResultElement:__request.OutputBody name:@"return"];
    return (KGFsuggestionsReply*)[__request createObject:__result type:[KGFsuggestionsReply class]];
}
-(NSMutableURLRequest*) createfindRequest:(KGFsuggestions*) arg0 __request:(KGFRequestResultHandler*) __request
{
    DDXMLElement *__methodElement=[__request writeElement:@"find" URI:@"http://service.suggestions.app/" parent:__request.Body];
    [self addAdornments:__methodElement];
             
    DDXMLElement* __arg0ItemElement=[__request writeElement:arg0 type:[KGFsuggestions class] name:@"arg0" URI:@"" parent:__methodElement skipNullProperty:YES];
    if(__arg0ItemElement!=nil)
    {
        [arg0 serialize:__arg0ItemElement __request: __request];
    }
    
    NSMutableURLRequest* __requestObj= [self createRequest:@""  __request:__request];
    return __requestObj;
}

-(KGFRequestResultHandler*) findAsync:(KGFsuggestions*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    KGFRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(KGFRequestResultHandler *__requestMgr) {
    id __res;
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[KGFHelper getResultElement:__request.OutputBody name:@"findResponse"];
        __res= (KGFfindResponse*)[__request createObject:__result type:[KGFfindResponse class]];
    }
    else
    {
        __res=__requestMgr.OutputFault;
    }
    
    IMP imp = [__target methodForSelector:__handler];
    void (*func)(id, SEL,id) = (void *)imp;
    func(__target, __handler,__res);
    }];
    return __request;
}

-(KGFRequestResultHandler*) findAsync:(KGFsuggestions*) arg0 __target:(id<KGFSoapServiceResponse>) __target
{
    KGFRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request callback:^(KGFRequestResultHandler *__requestMgr) {
    if(__requestMgr.OutputFault==nil)
    {
        DDXMLElement *__result=[KGFHelper getResultElement:__request.OutputBody name:@"findResponse"];
        [__target onSuccess:(KGFfindResponse*)[__request createObject:__result type:[KGFfindResponse class]]];
    }
    else
    {
        [__target onError:__requestMgr.OutputFault];
    }
    }];
    return __request;
}

-(KGFfindResponse*) find:(KGFsuggestions*) arg0 __error:(NSError**) __error 
{
    KGFRequestResultHandler* __request = [self CreateRequestResultHandler];        
    NSMutableURLRequest *__requestObj=[self createfindRequest:arg0 __request:__request];
    [self sendImplementation:__requestObj requestMgr:__request ];
    if(__request.OutputFault!=nil)
    {
        if(__error)
        {
            *__error=__request.OutputFault;
        }
        return nil;
    }
    DDXMLElement *__result=[KGFHelper getResultElement:__request.OutputBody name:@"findResponse"];
    return (KGFfindResponse*)[__request createObject:__result type:[KGFfindResponse class]];
}

-(KGFRequestResultHandler*) saveAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(KGFRequestResultHandler*) saveAsync:(NSString*) arg0 __target:(id<KGFSoapServiceResponse>) __target
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
    return nil;
}

-(void) save:(NSString*) arg0 __error:(NSError**) __error 
{
    /*This feature is available in Premium account, Check http://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account*/
}

@end
