//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.2
//
// Created by Quasar Development at 11-06-2014
//
//---------------------------------------------------


#import "KGFHelper.h"
#import "KGFsuggestionsReply.h"


@implementation KGFsuggestionsReply
@synthesize content;
@synthesize createTime;
@synthesize _id;
@synthesize suggestionsId;
@synthesize userId;

+ (KGFsuggestionsReply *)createWithXml:(DDXMLElement *)__node __request:(KGFRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KGFRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KGFHelper hasValue:__node name:@"content" index:0])
        {
            self.content = [[KGFHelper getNode:__node name:@"content" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"createTime" index:0])
        {
            self.createTime = [[KGFHelper getNode:__node name:@"createTime" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"id" index:0])
        {
            self._id = [[KGFHelper getNode:__node name:@"id" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"suggestionsId" index:0])
        {
            self.suggestionsId = [[KGFHelper getNode:__node name:@"suggestionsId" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"userId" index:0])
        {
            self.userId = [[KGFHelper getNode:__node name:@"userId" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KGFRequestResultHandler*) __request
{

             
    DDXMLElement* __contentItemElement=[__request writeElement:content type:[NSString class] name:@"content" URI:@"" parent:__parent skipNullProperty:YES];
    if(__contentItemElement!=nil)
    {
        [__contentItemElement setStringValue:self.content];
    }
             
    DDXMLElement* __createTimeItemElement=[__request writeElement:createTime type:[NSString class] name:@"createTime" URI:@"" parent:__parent skipNullProperty:YES];
    if(__createTimeItemElement!=nil)
    {
        [__createTimeItemElement setStringValue:self.createTime];
    }
             
    DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:YES];
    if(___idItemElement!=nil)
    {
        [___idItemElement setStringValue:self._id];
    }
             
    DDXMLElement* __suggestionsIdItemElement=[__request writeElement:suggestionsId type:[NSString class] name:@"suggestionsId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__suggestionsIdItemElement!=nil)
    {
        [__suggestionsIdItemElement setStringValue:self.suggestionsId];
    }
             
    DDXMLElement* __userIdItemElement=[__request writeElement:userId type:[NSString class] name:@"userId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__userIdItemElement!=nil)
    {
        [__userIdItemElement setStringValue:self.userId];
    }


}
@end
