//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.2
//
// Created by Quasar Development at 11-06-2014
//
//---------------------------------------------------



#import <Foundation/Foundation.h>

#import "KGFsuggestionsReply.h"
#import "KGFfindResponse.h"
#import "KGFsuggestions.h"
#import "DDXML.h"

@class KGFRequestResultHandler;

@protocol KGFSoapServiceResponse < NSObject>
- (void) onSuccess: (id) value;
- (void) onError: (NSError*) error;
@end


@interface KGFSuggestionsServiceImplServiceSoapBinding : NSObject
    
@property (retain, nonatomic) NSDictionary* Headers;
@property (retain, nonatomic) NSString* Url;
@property (nonatomic) BOOL ShouldAddAdornments;

- (id) init;
- (id) initWithUrl: (NSString*) url;

-(NSMutableURLRequest*) creategetReplyBySuggestIdRequest:(NSString*) arg0 __request:(KGFRequestResultHandler*) __request;
-(KGFsuggestionsReply*) getReplyBySuggestId:(NSString*) arg0 __error:(NSError**) __error;
-(KGFRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(KGFRequestResultHandler*) getReplyBySuggestIdAsync:(NSString*) arg0 __target:(id<KGFSoapServiceResponse>) __target;
-(NSMutableURLRequest*) createfindRequest:(KGFsuggestions*) arg0 __request:(KGFRequestResultHandler*) __request;
-(KGFfindResponse*) find:(KGFsuggestions*) arg0 __error:(NSError**) __error;
-(KGFRequestResultHandler*) findAsync:(KGFsuggestions*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(KGFRequestResultHandler*) findAsync:(KGFsuggestions*) arg0 __target:(id<KGFSoapServiceResponse>) __target;
-(void) save:(NSString*) arg0 __error:(NSError**) __error;
-(KGFRequestResultHandler*) saveAsync:(NSString*) arg0 __target:(id) __target __handler:(SEL) __handler;
-(KGFRequestResultHandler*) saveAsync:(NSString*) arg0 __target:(id<KGFSoapServiceResponse>) __target;
-(KGFRequestResultHandler*) CreateRequestResultHandler;   
-(NSMutableURLRequest*) createRequest :(NSString*) soapAction __request:(KGFRequestResultHandler*) __request; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(KGFRequestResultHandler*) requestMgr; 
-(void) sendImplementation:(NSMutableURLRequest*) request requestMgr:(KGFRequestResultHandler*) requestMgr callback:(void (^)(KGFRequestResultHandler *)) callback;

@end
