//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 3.0.3.2
//
// Created by Quasar Development at 11-06-2014
//
//---------------------------------------------------


#import "KGFHelper.h"
#import "KGFsuggestions.h"


@implementation KGFsuggestions
@synthesize content;
@synthesize createTime;
@synthesize customerId;
@synthesize _id;
@synthesize isReply;
@synthesize nickname;

+ (KGFsuggestions *)createWithXml:(DDXMLElement *)__node __request:(KGFRequestResultHandler*) __request
{
    if(__node == nil) { return nil; }
    return [[self alloc] initWithXml: __node __request:__request];
}

-(id)init {
    if ((self=[super init])) {
    }
    return self;
}

- (id) initWithXml: (DDXMLElement*) __node __request:(KGFRequestResultHandler*) __request{
    if(self = [self init])
    {
        if([KGFHelper hasValue:__node name:@"content" index:0])
        {
            self.content = [[KGFHelper getNode:__node name:@"content" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"createTime" index:0])
        {
            self.createTime = [[KGFHelper getNode:__node name:@"createTime" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"customerId" index:0])
        {
            self.customerId = [[KGFHelper getNode:__node name:@"customerId" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"id" index:0])
        {
            self._id = [[KGFHelper getNode:__node name:@"id" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"isReply" index:0])
        {
            self.isReply = [[KGFHelper getNode:__node name:@"isReply" index:0] stringValue];
        }
        if([KGFHelper hasValue:__node name:@"nickname" index:0])
        {
            self.nickname = [[KGFHelper getNode:__node name:@"nickname" index:0] stringValue];
        }
    }
    return self;
}

-(void) serialize:(DDXMLElement*)__parent __request:(KGFRequestResultHandler*) __request
{

             
    DDXMLElement* __contentItemElement=[__request writeElement:content type:[NSString class] name:@"content" URI:@"" parent:__parent skipNullProperty:YES];
    if(__contentItemElement!=nil)
    {
        [__contentItemElement setStringValue:self.content];
    }
             
    DDXMLElement* __createTimeItemElement=[__request writeElement:createTime type:[NSString class] name:@"createTime" URI:@"" parent:__parent skipNullProperty:YES];
    if(__createTimeItemElement!=nil)
    {
        [__createTimeItemElement setStringValue:self.createTime];
    }
             
    DDXMLElement* __customerIdItemElement=[__request writeElement:customerId type:[NSString class] name:@"customerId" URI:@"" parent:__parent skipNullProperty:YES];
    if(__customerIdItemElement!=nil)
    {
        [__customerIdItemElement setStringValue:self.customerId];
    }
             
    DDXMLElement* ___idItemElement=[__request writeElement:_id type:[NSString class] name:@"id" URI:@"" parent:__parent skipNullProperty:YES];
    if(___idItemElement!=nil)
    {
        [___idItemElement setStringValue:self._id];
    }
             
    DDXMLElement* __isReplyItemElement=[__request writeElement:isReply type:[NSString class] name:@"isReply" URI:@"" parent:__parent skipNullProperty:YES];
    if(__isReplyItemElement!=nil)
    {
        [__isReplyItemElement setStringValue:self.isReply];
    }
             
    DDXMLElement* __nicknameItemElement=[__request writeElement:nickname type:[NSString class] name:@"nickname" URI:@"" parent:__parent skipNullProperty:YES];
    if(__nicknameItemElement!=nil)
    {
        [__nicknameItemElement setStringValue:self.nickname];
    }


}
@end
